version: '2'
exclude_patterns:
  - 'build/'
  - 'node_modules/'
  - 'coverage/'
  - 'docs/'
  - 'src/setupTests.ts'
  # glue code should be ignored:
  - 'src/index.ts'

checks:
  method-lines:
    config:
      threshold: 50

---
engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 75
