name: NPM publish

on:
  push:
    tags:
      - '*'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build library
        run: yarn build

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
